### ISSUE TITLE
Support for BitBucket

### ISSUE THREAD

**Issue by roxanemace** [nikolajevp/changelog-updater#3]
[BitBucket](https://bitbucket.org/) uses a different url structure to compare tags. They are in the reverse order: `https://bitbucket.org/<OWNER>/<REPOSITORY>/branches/compare/HEAD..<TAG>`.

Here's an example: https://bitbucket.org/amalto/dev-service-typescript/branches/compare/HEAD..v1.1.0

I could submit a PR if you are interested.

**Comment by nikolajevp** [comment]
Yes sure! create pull request.

**Comment by nikolajevp** [comment]
It should work with bitbucket now 👍

**Comment by roxanemace** [comment]
Thanks a lot :)
